# Generated by Django 6.0.4 on 2026-06-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfollowup',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_followups', to='telecalling.paymenthistory'),
        ),
    ]
