# Generated by Django 6.0.4 on 2026-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0002_alter_paymentfollowup_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
