# Generated by Django 6.0.4 on 2026-06-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0004_api_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.IntegerField()),
                ('data', models.JSONField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telecalling_deleted_data_log',
            },
        ),
    ]
