# Generated by Django 6.0.4 on 2026-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0006_dropdowncategory_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropdowncategory',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
