# Generated by Django 6.0.4 on 2026-06-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0007_alter_dropdown_name_alter_dropdown_sub_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='telecalling.dropdown'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_plans',
            field=models.ManyToManyField(blank=True, related_name='course_plans', to='telecalling.dropdown'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_timings',
            field=models.ManyToManyField(blank=True, related_name='course_timings', to='telecalling.dropdown'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
