# Generated by Django 6.0.4 on 2026-06-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0008_course_course_names_course_course_plans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_plan',
        ),
    ]
