# Generated by Django 6.0.4 on 2026-06-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0009_remove_course_course_name_remove_course_course_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_names',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_plans',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_timings',
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('courseplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_plan', to='telecalling.dropdown')),
            ],
            options={
                'db_table': 'telecalling_course_plan',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='telecalling.courseplan'),
        ),
        migrations.CreateModel(
            name='CourseTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('coursetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_timing', to='telecalling.dropdown')),
            ],
            options={
                'db_table': 'telecalling_course_time',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_timings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='telecalling.coursetiming'),
        ),
    ]
