# Generated by Django 6.0.4 on 2026-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0010_rename_course_names_course_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_name', models.CharField(max_length=100)),
                ('referal_number', models.CharField(max_length=15)),
                ('admin_check', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'telecalling_referal_details',
            },
        ),
    ]
