# Generated by Django 6.0.4 on 2026-06-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0011_referaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='referaldetails',
            name='referal_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='telecalling.lead'),
        ),
    ]
