# Generated by Django 6.0.4 on 2026-06-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0013_campaignname_coursename_education_filterleads_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calldetails',
            old_name='key_objective',
            new_name='select_tag',
        ),
        migrations.RenameField(
            model_name='calldetails',
            old_name='conversation_outcome',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='lead',
            name='current_status',
            field=models.CharField(default='working', max_length=50),
        ),
    ]
