# Generated by Django 6.0.4 on 2026-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0014_rename_key_objective_calldetails_select_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisconnectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'telecalling_disconnect_stage',
            },
        ),
    ]
