# Generated by Django 6.0.4 on 2026-06-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0015_disconnectstage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_plan',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_time',
            new_name='time',
        ),
    ]
