# Generated by Django 6.0.4 on 2026-06-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0016_rename_course_name_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='plan',
            new_name='course_plan',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='time',
            new_name='course_time',
        ),
        migrations.RenameField(
            model_name='coursename',
            old_name='coursename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='courseplan',
            old_name='courseplan',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='coursetiming',
            old_name='coursetime',
            new_name='time',
        ),
    ]
