# Generated by Django 6.0.4 on 2026-06-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0018_rename_course_name_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'telecalling_filter_payment',
            },
        ),
        migrations.CreateModel(
            name='SubFilterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('filter_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_payments', to='telecalling.filterpayment')),
            ],
            options={
                'db_table': 'telecalling_subfilter_payment',
            },
        ),
    ]
