# Generated by Django 6.0.4 on 2026-06-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0019_filterpayment_subfilterpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'telecalling_amount_stage',
            },
        ),
        migrations.CreateModel(
            name='PaymentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'telecalling_payment_stage',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'telecalling_payment_status',
            },
        ),
        migrations.RemoveField(
            model_name='subfilterpayment',
            name='filter_payment',
        ),
        migrations.DeleteModel(
            name='SubFilterLead',
        ),
        migrations.DeleteModel(
            name='SubFilterPayment',
        ),
    ]
