# Generated by Django 6.0.4 on 2026-06-29 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0020_amountstage_paymentstage_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossleaddetail',
            name='sub_reason',
        ),
        migrations.AlterField(
            model_name='lossleaddetail',
            name='main_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telecalling.selecttag'),
        ),
    ]
