# Generated by Django 6.0.4 on 2026-06-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0021_remove_lossleaddetail_sub_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payment_status',
            new_name='due_stage',
        ),
    ]
