# Generated by Django 6.0.4 on 2026-06-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0022_rename_payment_status_paymenthistory_due_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursetiming',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
