# Generated by Django 6.0.4 on 2026-06-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0024_alter_calldetails_select_tag_alter_calldetails_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disconnecteddetails',
            name='select_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnect', to='telecalling.disconnectstage'),
        ),
    ]
