# Generated by Django 6.0.4 on 2026-06-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0025_alter_disconnecteddetails_select_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetails',
            name='select_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='telecalling.selecttag'),
        ),
        migrations.AlterField(
            model_name='calldetails',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_tag', to='telecalling.stages'),
        ),
    ]
