# Generated by Django 6.0.4 on 2026-06-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0026_alter_calldetails_select_tag_alter_calldetails_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='disconnecteddetails',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disconnecteddetails',
            name='retry_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
