# Generated by Django 6.0.4 on 2026-07-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0030_remove_paymenthistory_due_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='payment_status_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='due_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telecalling.paymentstage'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='payment_status',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
