# Generated by Django 6.0.4 on 2026-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0031_remove_paymentinfo_payment_status_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='due_stage_id',
            new_name='due_stage',
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_status',
            field=models.IntegerField(null=True),
        ),
    ]
