# Generated by Django 6.0.4 on 2026-07-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0032_rename_due_stage_id_paymenthistory_due_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(null=True)),
                ('total_leads', models.IntegerField(default=0)),
                ('new_leads', models.IntegerField(default=0)),
                ('call_spoked', models.IntegerField(default=0)),
                ('not_respond', models.IntegerField(default=0)),
                ('follow_up', models.IntegerField(default=0)),
                ('pending_follow_up', models.IntegerField(default=0)),
                ('partial_payment', models.IntegerField(default=0)),
                ('full_payment', models.IntegerField(default=0)),
                ('total_expected_conversion', models.IntegerField(default=0)),
                ('actual_expected_conversion', models.IntegerField(default=0)),
                ('notes_for_manager', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telecalling_daily_report',
                'ordering': ['-report_date'],
                'unique_together': {('user', 'report_date')},
            },
        ),
    ]
