# Generated by Django 6.0.4 on 2026-07-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0033_dailyreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
    ]
