# Generated by Django 6.0.4 on 2026-08-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0034_alter_dailyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecalling.lead'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='display_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priority',
            name='display_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priority',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telecalling.pipelinestage'),
        ),
        migrations.AddField(
            model_name='selecttag',
            name='display_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
