# Generated by Django 6.0.4 on 2026-08-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_team_usertarget'),
        ('telecalling', '0035_notification_lead_pipelinestage_display_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='adm.team'),
        ),
    ]
