# Generated by Django 6.0.4 on 2026-08-06 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telecalling', '0035_notification_lead_pipelinestage_display_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApprovedLossLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_remarks', models.TextField(blank=True, null=True)),
                ('can_retarget', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loss_leads', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_loss_record', to='telecalling.lead')),
                ('main_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telecalling.selecttag')),
            ],
            options={
                'db_table': 'adm_approved_loss_lead',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminLossActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_action_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_loss_action_logs', to='telecalling.lead')),
                ('new_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_loss_reassignments', to=settings.AUTH_USER_MODEL)),
                ('previous_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_loss_reassignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_loss_action_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
