# Generated by Django 6.0.4 on 2026-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlossactionlog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
    ]
