# Generated by Django 6.0.4 on 2026-08-11 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_adminapprovedlosslead_created_at_and_more'),
        ('telecalling', '0035_notification_lead_pipelinestage_display_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLeadReassignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_calls_count', models.IntegerField(default=0)),
                ('previous_call_history', models.JSONField(blank=True, default=list, null=True)),
                ('reassigned_reason', models.TextField(blank=True, null=True)),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassign_history', to='telecalling.lead')),
                ('new_telecaller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_to_history', to=settings.AUTH_USER_MODEL)),
                ('previous_telecaller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from_history', to=settings.AUTH_USER_MODEL)),
                ('reassigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_by_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_lead_reassign_history',
                'ordering': ['-reassigned_at'],
            },
        ),
    ]
